describe('Didarul', () => {
    it('Test', () => {
      cy.visit('https://uat-crm.oss.net.bd/')
      /*cy.wait(3000)*/
      cy.get('header>div>div>a').contains('Login').click()
      cy.get('div[class="signup-body"]').click()
      cy.get('input[id="username"]').type('sqatest1@ba-systems.com')
      cy.get('input[name="password"]').type('Sqa@!@#098_baT)')
      cy.get('input[name="login"]').click()
      cy.get('li>a[href="https://uat-crm.oss.net.bd/issue/lists"]').click()
      cy.get('a[href="https://uat-crm.oss.net.bd/issue/create-new-issue"]').click()
      cy.get('input[value="To Do"]').click()
      cy.get('span[id="select2-project_id-container"]').click()
      cy.get('span>span>input[class="select2-search__field"]').type('Anamul Hoque Jihad Khan{enter}')
      cy.get('select[name="milestone_id"]').select('391')
      cy.get('select[name="task_id"]').select('994')
      cy.get('input[name="issue_title"]').type('Test Title')
      cy.get('p[class="ck-placeholder"]').type('Dear Concern All of these transactions are failed')
      cy.get('select[id="severity"]').select('Major')
      cy.get('div>input[name="impact"][value="High"]').click()
      cy.get('select[id="reproducibility"]').select('Random')
      cy.get('input[name="reproduction_steps"]').type('Sample text. Sample text.')
      cy.get('div>div[id="team_data_div"]').click()
      cy.get('span>span>input[class="select2-search__field"]').type('accounts{enter}')
      cy.get('div>div[id="assign_to_div"]').click()
      cy.get('span>span>input[class="select2-search__field"]').type('nuzhat@batworld.com{enter}')
      cy.get('div>input[name="target_date"]').clear()
      cy.get('div>input[name="target_date"]').invoke('val', '25-Oct-2024 19:00').trigger('change').blur()
      cy.get('div[style="margin-bottom: 5px"]').contains('Email').click()
      cy.get('div[style="margin-bottom: 5px"]').contains('SMS').click()
      cy.get('label[class="col-md-3 col-xs-3 specialRadiodiv"]').contains('URL').click()
      cy.get('input[id="URL"]').type('https://uat-crm.oss.net.bd/issue/create-new-issue')
      cy.get('div>select[id="relationships"').select('None')
      cy.get('div>button[type="submit"]').click()
    })
  })